defaults:
  - base

data_path: /tmp
logging: True
unlabeled: False

model:
    pretrained: True
    projector_dim: 8_192

param:
    lr: 5e-4
    batch_size: 1_024

disc:
    alpha: 0.0
    mult: 0.0

logger:
    project: pretraining-pacs