name: Base
logging: True
unlabeled: False

decorrelate_embeddings: False

model:
    pretrained: True

data:
    name: pacs
    path: /data
    color_aug: False

param:
    lr: 1e-3
    batch_size: 64

trainer:
    max_epochs: 30
    check_val_every_n_epoch: 1
    step_lr_stepsize: 20

mixstyle:
    active: False
    p: 1.0 
    alpha: 0.1
    eps: 1e-6

disc:
    active: False
    alpha: 0.1

logger:
    log_every_n_steps: 5
    project: supervised-experiments-base