defaults:
    - base

logging: True

model:
    pretrained: true

data:
    name: dr
    num_classes: 5
    
    color_aug: True

trainer:
    check_val_every_n_epoch: 1
    max_epochs: 100

mixstyle:
    active: False

disc:
    active: False

logger:
    log_every_n_steps: 10
    project: supervised-experiments-4-dr