defaults:
    - base

name: Debug
logging: True

data:
    num_classes: 7

trainer:
    max_epochs: 60

disc:
    active: True
    alpha: 0.1

mixstyle:
    active: True
    p: 1.0
    alpha: 0.1
    eps: 1e-6

logger:
    project: supervised-experiments-pacs